### ISSUE TITLE
Form to reserve a board game on Game Library page

### ISSUE THREAD

**Issue by AlexandraH-code** [AlexandraH-code/boardwalk-games#7]
**User Story:** 
As a Board Game Enthusiast, I want to reserve a board game from the list of available games, so I can ensure it's available for me when I visit the shop.

**Acceptance Criteria:**

- [x] A reservation form is available on the Game Library page
- [x] The user can fill out their selected game, name, contact information, and preferred date for the reservation.

**Tasks:**

- [x] Create a reservation form with fields for the user's name, contact information, preferred date and select which game they want to reserve.
